# Default values for app.
# fullnameOverride: "" # DONOT use this update in the chard name instead
nameOverride: "drunk-test-app"

imageCredentials:
  name: "drunkcoding-acr-secret"
  registry: "drunkcoding.net"
  username: "drunk"
  password: "coding"

global:
  image: "baoduy2412/astro-blog"
  tag: "latest"
  imagePullPolicy: "IfNotPresent"
  storageClassName: "111"
  imagePullSecret: "drunkcoding-acr-secret"
  initContainer:
    image: "baoduy2412/astro-blog"
    command: ["sh", "-c", "echo Init complete;"]

#Environments variables through configMap and secrets
env:
  env1: "hello"
  env2: "drunkcoding"

configMap:
  hello: "1"
  log: "123"

configFrom:
  - name_of_other_config

secrets:
  connectionString: "ABC"
  redis: "BAC123"

secretProvider:
  enabled: true
  name: "my-secret-class"
  provider:
    name: aws
    tenantId: "your-tenant-id"
    vaultName: "your-vault-name"
    userAssignedIdentityID: "your-identity-id"
    usePodIdentity: false
    useWorkloadIdentity: false
  objects:
    - objectName: my-secret-1
      objectType: cert
      objectFormat: pfx
      objectEncoding: base64
    - objectName: my-secret-2
      objectType: secret
secretFrom:
  - name_of_other_secret

tlsSecrets:
  cloudflare:
    enabled: true
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ4RENDQXRpZ0F3SUJBZ0lVSkZUaXl3bm51ZEJPODVSUkx0bGQvTU90SGpnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZMHhDekFKQmdOVkJBWVRBbE5ITVJJd0VBWURWUVFJREFsVGFXNW5ZWEJ2Y21VeEVqQVFCZ05WQkFjTQpDVk5wYm1kaGNHOXlaVEVTTUJBR0ExVUVDZ3dKUkdWMklFeHZZMkZzTVF3d0NnWURWUVFMREFORVRGVXhIakFjCkJna3Foa2lHOXcwQkNRRVdEMlZ0WVdsc1FHUmxkaTVzYjJOaGJERVVNQklHQTFVRUF3d0xLaTVrWlhZdWJHOWoKWVd3d0lCY05NalF3TkRBeU1UTXdNakExV2hnUE1qRXlOREF6TURreE16QXlNRFZhTUlHTk1Rc3dDUVlEVlFRRwpFd0pUUnpFU01CQUdBMVVFQ0F3SlUybHVaMkZ3YjNKbE1SSXdFQVlEVlFRSERBbFRhVzVuWVhCdmNtVXhFakFRCkJnTlZCQW9NQ1VSbGRpQk1iMk5oYkRFTU1Bb0dBMVVFQ3d3RFJFeFZNUjR3SEFZSktvWklodmNOQVFrQkZnOWwKYldGcGJFQmtaWFl1Ykc5allXd3hGREFTQmdOVkJBTU1DeW91WkdWMkxteHZZMkZzTUlJQklqQU5CZ2txaGtpRwo5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNVoxdWxVV2ZDcmQ3Rkwwb2lFWXZZUjk3dlhCazZHckdEb2xuCmNodHBOdkNoNG1SbUtuejRtM05tQ2pUNW03cGJxWGlJazh6cE05a250a2E4ejZBRmFDYWEvc296aWE2V0VSOWIKWHZlem5pY0JRc3lDZ3NPb3Y0RFNDMC82VEpaKzhmcXlBWTNQL212djRlYlVPRWhuNlVlQXAzbEQvZDQyUlpBYQoxQi9LR1RLN0x6OVlSZUFNMDNMZnBHQkUwaStrQ1RTVGw1d0JRazJteUJ3S3cxYzhzU2llNnhGa2dnZ1BzOU9wCjBUa2dTYi9neFkzSHdxS0czOGRqb0lhMjVsVzNyOUIxdUViWjZGLy91dHVCT3p1MERZZE1LQ0ZRVlBtUUlNa3YKUkc0ZllOSFBUb2IxQ0d1d1RLK2IxWHJZazBzSG9FUVlSWnc5cFhIMnpYQm5UUjlJbFFJREFRQUJvMFF3UWpBaApCZ05WSFJFRUdqQVlnZ3NxTG1SbGRpNXNiMk5oYklJSlpHVjJMbXh2WTJGc01CMEdBMVVkRGdRV0JCUm5odUJuCnptcFNMNXpkMnBWVkUzNFJUbjVLUXpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQXFMWUpwOTJmbHZyOWZnKzEKZkNIcWdmQm1jWlNjVUlwUEJBOFp4RjZHQXgrUkp6T09vR3dsK2p2Qm9CRU1jNlJFOHBjTGl2YlRmV0VUa1kwOQp3QmhyQzBHaWduQVd2UVZFdERNNkpnaEw5cXZwbjI0cXJMQ0VzUVFkU3RCRmF6MkF4M2wxQjZvbmg1VTZybCtICkZISzNSakJEdjJHekwrbFFRR1NPQjZHdzJvNlhLbW9iejA3OVJ4UVYzTlF1L2YzWm9tcE1SeE9aejBIVzRFUWEKYUdrRjMybUZGczVoQVJQdG5PcGZVVjYrK245ejI1Z044UVg5RDNIUXRuaGk5LzJDVnR4OUNRUFFJS2RhN3pETQpoZFIyUkZ0N3RjNm9MemxjckY3TDVHR2RJMlVEQnIyejlLdHRhOVZIaFlrUmRxajV5TnkxUDNDU0I0ZWY1bVV1CmhVYXVRQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRGxuVzZWUlo4S3Qzc1UKdlNpSVJpOWhIM3U5Y0dUb2FzWU9pV2R5RzJrMjhLSGlaR1lxZlBpYmMyWUtOUG1idWx1cGVJaVR6T2t6MlNlMgpScnpQb0FWb0pwcit5ak9KcnBZUkgxdGU5N09lSndGQ3pJS0N3NmkvZ05JTFQvcE1sbjd4K3JJQmpjLythKy9oCjV0UTRTR2ZwUjRDbmVVUDkzalpGa0JyVUg4b1pNcnN2UDFoRjRBelRjdCtrWUVUU0w2UUpOSk9YbkFGQ1RhYkkKSEFyRFZ6eXhLSjdyRVdTQ0NBK3owNm5ST1NCSnYrREZqY2ZDb29iZngyT2docmJtVmJldjBIVzRSdG5vWC8rNgoyNEU3TzdRTmgwd29JVkJVK1pBZ3lTOUViaDlnMGM5T2h2VUlhN0JNcjV2VmV0aVRTd2VnUkJoRm5EMmxjZmJOCmNHZE5IMGlWQWdNQkFBRUNnZ0VBQU14L2FmMklCQjJIVEJjc1lPejlsVFRxMVVuaXovd3ZIRFhXS2t0MkhqN1EKRVYyUURXM0ozNkNUSmszdzRGM1JtOUZUaUZBYUw1Zjl6MkNIbjZGSzQ0WGUzQ3dQNmRhMXB2R1krOGVZMUdBRwpYUmtoQ3h0ckp0OW4yNm8za0xTbFZHb3UzRnFGOHJpbGFQL0lsVG1MUXdDQXJoUjU3QlF0MUNnZ0w4UzhpMEhrClBOOHJKd08zcktGWGdYdFVWMWVFQ0YzNVpEbDRrdlhnVDBlVGFuR3dxblRIZENZYVhzT1lQd2FCSm5EMjlzUjIKYzlhUFVlR2hpWW44d0RKMFNhVThBUzRBQzVBK3lKaEVUUHFsWGkxV2RscjRxOGEzMnVCYks0T3VKRTlmM081MgpQd2dtTndUVUNCYldQb2ZpdCt4dkJJWFlQQ1paUUxsYzU5UHVCWitHQVFLQmdRRDNWYzR6aXZtaDVBMDdFSi9oCmhvS1V2allyVDhtbDV5SXRwNmtncGwvQ0R5bmYvamIzKzhUWXlyelVSbGt1K1dGT1BVZkYwc0RQdEVWdGEyYXMKY1NjeDVuL09HcWd5aXQ3QzFzUXl6aFQxQ1BOa0luTmNaMGRYeWpoZXRxbFR5ckIxNUVaVnRjWGN0Tng2QkdBWApzQU92cEZnUU55TXY0SmdMc213NzJzNlE0UUtCZ1FEdHFMUjhHbndaczk3QTJHMS92QjRLN3VwM3h0cHhVKzFxCld2YWYvRWxTRENtRGYxRGIxT1lDa0tyWStNZm9vZHIxQUdaa1A2ZjdlR1J4Z2w1ZnJkdlQ2djV2OXg1RG5YTEMKT3B0b2N4aU45WDZMSE5KTDluRUxrajRjNm1ITFBpKy9DVDg0OVdnRDkyazJ2TCtHdDFHRDBvaGZwRVlUVFNSdwpnV0JvbElLS05RS0JnQXpEZXM2aUgxdkJYd1ZyU0RUbE1odm03UGl6TjE2K1hMOHFaY252akFXQnJ0R0dWdVBaCk5FRlR4UWJYVW9iZ0M2dHo4aDQ5VUFIbjlhVTk0NkNHZmxWTzVjMkhCcU1GRTVYT2EzV0x1UDBrSnh0Rnc5cEMKNGlXZm8rVVBYQkdjNWhwUFcyblU1WThNTGt5RnFVZlBwNEVLNUJpQ0graTZtRjRTS1ErMXJPOUJBb0dCQU1MdQovTk5LZWY0dkRnZkp2YzduQXhGZXRFejRlMVkzUytaUHBEakhtM0JENzQwZlViaHVvUmI3aUZjZGdBTnROd1o4CmhIKzN3dFkrQXMwajdMcTRCVGFHYXBwMTdJbnpUQnpLSzR4NTAyc2xNTjEwRDM0bExzWVo5djZLdFJvYThOalcKQWRoN1dnemUwNXNGS0dlY1Y2MHpjNDVYVk84aCtFQ2JyZk01MVBUOUFvR0FkbE1Pdm1sOUJOWDg3ekVaYXpOMgo5YmFMdFp1MG9kS1YxNkNRMmIxY05IUVZ3MEJTTEQxUlZNZVM1REpsdmM0bEptR25DMnJLb3lESFdOQjg2cERFCk8vT0J2SG5CM0hvYVZwelRPR3pyS29QYW5OWDlRTGwrNXYwSkJIUXRmVDBrWTlGbWVuUi9ieXBYNWc0cCtDUzgKcklpcmJHNC9GM0FpSHoyZmEyTkNQM289Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  dev-local:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ4RENDQXRpZ0F3SUJBZ0lVSkZUaXl3bm51ZEJPODVSUkx0bGQvTU90SGpnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZMHhDekFKQmdOVkJBWVRBbE5ITVJJd0VBWURWUVFJREFsVGFXNW5ZWEJ2Y21VeEVqQVFCZ05WQkFjTQpDVk5wYm1kaGNHOXlaVEVTTUJBR0ExVUVDZ3dKUkdWMklFeHZZMkZzTVF3d0NnWURWUVFMREFORVRGVXhIakFjCkJna3Foa2lHOXcwQkNRRVdEMlZ0WVdsc1FHUmxkaTVzYjJOaGJERVVNQklHQTFVRUF3d0xLaTVrWlhZdWJHOWoKWVd3d0lCY05NalF3TkRBeU1UTXdNakExV2hnUE1qRXlOREF6TURreE16QXlNRFZhTUlHTk1Rc3dDUVlEVlFRRwpFd0pUUnpFU01CQUdBMVVFQ0F3SlUybHVaMkZ3YjNKbE1SSXdFQVlEVlFRSERBbFRhVzVuWVhCdmNtVXhFakFRCkJnTlZCQW9NQ1VSbGRpQk1iMk5oYkRFTU1Bb0dBMVVFQ3d3RFJFeFZNUjR3SEFZSktvWklodmNOQVFrQkZnOWwKYldGcGJFQmtaWFl1Ykc5allXd3hGREFTQmdOVkJBTU1DeW91WkdWMkxteHZZMkZzTUlJQklqQU5CZ2txaGtpRwo5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNVoxdWxVV2ZDcmQ3Rkwwb2lFWXZZUjk3dlhCazZHckdEb2xuCmNodHBOdkNoNG1SbUtuejRtM05tQ2pUNW03cGJxWGlJazh6cE05a250a2E4ejZBRmFDYWEvc296aWE2V0VSOWIKWHZlem5pY0JRc3lDZ3NPb3Y0RFNDMC82VEpaKzhmcXlBWTNQL212djRlYlVPRWhuNlVlQXAzbEQvZDQyUlpBYQoxQi9LR1RLN0x6OVlSZUFNMDNMZnBHQkUwaStrQ1RTVGw1d0JRazJteUJ3S3cxYzhzU2llNnhGa2dnZ1BzOU9wCjBUa2dTYi9neFkzSHdxS0czOGRqb0lhMjVsVzNyOUIxdUViWjZGLy91dHVCT3p1MERZZE1LQ0ZRVlBtUUlNa3YKUkc0ZllOSFBUb2IxQ0d1d1RLK2IxWHJZazBzSG9FUVlSWnc5cFhIMnpYQm5UUjlJbFFJREFRQUJvMFF3UWpBaApCZ05WSFJFRUdqQVlnZ3NxTG1SbGRpNXNiMk5oYklJSlpHVjJMbXh2WTJGc01CMEdBMVVkRGdRV0JCUm5odUJuCnptcFNMNXpkMnBWVkUzNFJUbjVLUXpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQXFMWUpwOTJmbHZyOWZnKzEKZkNIcWdmQm1jWlNjVUlwUEJBOFp4RjZHQXgrUkp6T09vR3dsK2p2Qm9CRU1jNlJFOHBjTGl2YlRmV0VUa1kwOQp3QmhyQzBHaWduQVd2UVZFdERNNkpnaEw5cXZwbjI0cXJMQ0VzUVFkU3RCRmF6MkF4M2wxQjZvbmg1VTZybCtICkZISzNSakJEdjJHekwrbFFRR1NPQjZHdzJvNlhLbW9iejA3OVJ4UVYzTlF1L2YzWm9tcE1SeE9aejBIVzRFUWEKYUdrRjMybUZGczVoQVJQdG5PcGZVVjYrK245ejI1Z044UVg5RDNIUXRuaGk5LzJDVnR4OUNRUFFJS2RhN3pETQpoZFIyUkZ0N3RjNm9MemxjckY3TDVHR2RJMlVEQnIyejlLdHRhOVZIaFlrUmRxajV5TnkxUDNDU0I0ZWY1bVV1CmhVYXVRQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRGxuVzZWUlo4S3Qzc1UKdlNpSVJpOWhIM3U5Y0dUb2FzWU9pV2R5RzJrMjhLSGlaR1lxZlBpYmMyWUtOUG1idWx1cGVJaVR6T2t6MlNlMgpScnpQb0FWb0pwcit5ak9KcnBZUkgxdGU5N09lSndGQ3pJS0N3NmkvZ05JTFQvcE1sbjd4K3JJQmpjLythKy9oCjV0UTRTR2ZwUjRDbmVVUDkzalpGa0JyVUg4b1pNcnN2UDFoRjRBelRjdCtrWUVUU0w2UUpOSk9YbkFGQ1RhYkkKSEFyRFZ6eXhLSjdyRVdTQ0NBK3owNm5ST1NCSnYrREZqY2ZDb29iZngyT2docmJtVmJldjBIVzRSdG5vWC8rNgoyNEU3TzdRTmgwd29JVkJVK1pBZ3lTOUViaDlnMGM5T2h2VUlhN0JNcjV2VmV0aVRTd2VnUkJoRm5EMmxjZmJOCmNHZE5IMGlWQWdNQkFBRUNnZ0VBQU14L2FmMklCQjJIVEJjc1lPejlsVFRxMVVuaXovd3ZIRFhXS2t0MkhqN1EKRVYyUURXM0ozNkNUSmszdzRGM1JtOUZUaUZBYUw1Zjl6MkNIbjZGSzQ0WGUzQ3dQNmRhMXB2R1krOGVZMUdBRwpYUmtoQ3h0ckp0OW4yNm8za0xTbFZHb3UzRnFGOHJpbGFQL0lsVG1MUXdDQXJoUjU3QlF0MUNnZ0w4UzhpMEhrClBOOHJKd08zcktGWGdYdFVWMWVFQ0YzNVpEbDRrdlhnVDBlVGFuR3dxblRIZENZYVhzT1lQd2FCSm5EMjlzUjIKYzlhUFVlR2hpWW44d0RKMFNhVThBUzRBQzVBK3lKaEVUUHFsWGkxV2RscjRxOGEzMnVCYks0T3VKRTlmM081MgpQd2dtTndUVUNCYldQb2ZpdCt4dkJJWFlQQ1paUUxsYzU5UHVCWitHQVFLQmdRRDNWYzR6aXZtaDVBMDdFSi9oCmhvS1V2allyVDhtbDV5SXRwNmtncGwvQ0R5bmYvamIzKzhUWXlyelVSbGt1K1dGT1BVZkYwc0RQdEVWdGEyYXMKY1NjeDVuL09HcWd5aXQ3QzFzUXl6aFQxQ1BOa0luTmNaMGRYeWpoZXRxbFR5ckIxNUVaVnRjWGN0Tng2QkdBWApzQU92cEZnUU55TXY0SmdMc213NzJzNlE0UUtCZ1FEdHFMUjhHbndaczk3QTJHMS92QjRLN3VwM3h0cHhVKzFxCld2YWYvRWxTRENtRGYxRGIxT1lDa0tyWStNZm9vZHIxQUdaa1A2ZjdlR1J4Z2w1ZnJkdlQ2djV2OXg1RG5YTEMKT3B0b2N4aU45WDZMSE5KTDluRUxrajRjNm1ITFBpKy9DVDg0OVdnRDkyazJ2TCtHdDFHRDBvaGZwRVlUVFNSdwpnV0JvbElLS05RS0JnQXpEZXM2aUgxdkJYd1ZyU0RUbE1odm03UGl6TjE2K1hMOHFaY252akFXQnJ0R0dWdVBaCk5FRlR4UWJYVW9iZ0M2dHo4aDQ5VUFIbjlhVTk0NkNHZmxWTzVjMkhCcU1GRTVYT2EzV0x1UDBrSnh0Rnc5cEMKNGlXZm8rVVBYQkdjNWhwUFcyblU1WThNTGt5RnFVZlBwNEVLNUJpQ0graTZtRjRTS1ErMXJPOUJBb0dCQU1MdQovTk5LZWY0dkRnZkp2YzduQXhGZXRFejRlMVkzUytaUHBEakhtM0JENzQwZlViaHVvUmI3aUZjZGdBTnROd1o4CmhIKzN3dFkrQXMwajdMcTRCVGFHYXBwMTdJbnpUQnpLSzR4NTAyc2xNTjEwRDM0bExzWVo5djZLdFJvYThOalcKQWRoN1dnemUwNXNGS0dlY1Y2MHpjNDVYVk84aCtFQ2JyZk01MVBUOUFvR0FkbE1Pdm1sOUJOWDg3ekVaYXpOMgo5YmFMdFp1MG9kS1YxNkNRMmIxY05IUVZ3MEJTTEQxUlZNZVM1REpsdmM0bEptR25DMnJLb3lESFdOQjg2cERFCk8vT0J2SG5CM0hvYVZwelRPR3pyS29QYW5OWDlRTGwrNXYwSkJIUXRmVDBrWTlGbWVuUi9ieXBYNWc0cCtDUzgKcklpcmJHNC9GM0FpSHoyZmEyTkNQM289Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K

  drunk-seft:
    crtFile: "certs/drunkcoding.net.crt"
    keyFile: "certs/drunkcoding.net.key"
    caFile: "certs/drunkcoding.net-ca.crt"

# The flag to disable pod-deployment incase of deployment
deployment:
  enabled: true
  ports:
    http: 8080
    tcp: 9090
  liveness: "/healthz"
  #readiness: "/healthz/ready"
  args:
    - tunnel
    - "--no-autoupdate"
    - run
    - "--token"
    - $(token)
  podAnnotations:
    testMe: drunk-coding
  replicaCount: 1
  strategy:
    type: "RollingUpdate" # or Recreate
    maxSurge: "1" # default 1
    maxUnavailable: "1" # default 1

# The flag to disable pod-deployment incase of statefulset deployment
statefulset:
  enabled: true
  ports:
    http: 8080
    tcp: 9090
  replicaCount: 1
  liveness: "/healthz"
  #readiness: "/healthz/ready"
  args:
    - tunnel
    - "--no-autoupdate"
    - run
    - "--token"
    - $(token)
  podAnnotations:
    testMe: drunk-coding

cronJobs:
  - name: "drunk-cjob-1"
    schedule: "* 0 * * *"
    args:
      - hello
  - name: "drunk-cjob-2"
    schedule: "* 0 * * *"
    restartPolicy: Always
    command:
      - hello-1
      - hello-2

jobs:
  - name: "drunk-job-1"
    args:
      - hello
  - name: "drunk-job-2"
    restartPolicy: Always
    command:
      - hello-1
      - hello-2

volumes:
  data-vol:
    size: "2Gi"
    storageClassName: "abc"
    accessMode: "ReadWriteOnce"
    mountPath: "/data"
    subPath: "abc.dev"
    readOnly: false
  other-vol:
    size: "2Gi"
    accessMode: "ReadWriteOnce"
    mountPath: "/data"
    subPath: "abc.dev"
    readOnly: false
  tmp:
    mountPath: "/tmp"
    readOnly: false
    emptyDir: true

serviceAccount:
  enabled: true
  annotations: {}

podAnnotations: {}

podSecurityContext:
  fsGroup: 10000
  runAsUser: 10000
  runAsGroup: 10000
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: hello.drunkcoding.net
      port: 8080
    - host: api.drunkcoding.net
      port: 9090
  tls: chart-example-tls

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  #targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

# Allow all ingress, restrict egress to 192.168.253.253 only
networkPolicies:
  - name: allow-all-ingress-restrict-egress
    enabled: true
    policyTypes:
      - Ingress
      - Egress
    ingress:
      - {} # Allow all ingress
    egress:
      - to:
          - ipBlock:
              cidr: 192.168.253.253/32

